const itemConstants = {
  REDIRECT_SEARCH_ITEMS: 'mlapp/item/REDIRECT_SEARCH_ITEMS',
  REQUEST_SEARCH_ITEMS: 'mlapp/item/REQUEST_SEARCH_ITEMS',
  SET_SEARCHED_ITEMS: 'mlapp/item/SET_SEARCHED_ITEMS',
  SET_LOADING_SEARCH_ITEMS: 'mlapp/item/SET_LOADING_SEARCH_ITEMS',
  SET_ERROR_SEARCH_ITEMS: 'mlapp/item/SET_ERROR_SEARCH_ITEMS',
  REQUEST_FETCH_ITEM: 'mlapp/item/REQUEST_FETCH_ITEM',
  SET_FETCHED_ITEM: 'mlapp/item/SET_FETCHED_ITEM',
  SET_LOADING_FETCH_ITEM: 'mlapp/item/SET_LOADING_FETCH_ITEM',
  SET_ERROR_FETCH_ITEM: 'mlapp/item/SET_ERROR_FETCH_ITEM',
};

export default itemConstants;
